# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: ryutah/gcloud-gaego:180.0.0

    working_directory: /go/src/github.com/ryutah/circle-ci-sample
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: goapp get -u github.com/golang/dep/cmd/dep
      - run:
          name: Run unit tests
          command: goapp test -v ./...
      - run: sh deploy.sh
